using NguyenHoangNgocChauBusinessObjects.DAO;
using NguyenHoangNgocChauBusinessObjects.Models;
namespace NguyenHoangNgocChauBusinessObjects.Repositories;
public interface IAccountRepository { Task<SystemAccount?> FindLoginAsync(string email,string password); Task<List<SystemAccount>> SearchAsync(string? q); Task<SystemAccount?> GetAsync(short id); Task<bool> EmailExistsAsync(string email,short? excludeId); Task SaveAsync(SystemAccount x,bool add); Task<bool> DeleteAsync(short id); }
public class AccountRepository(AccountDAO dao) : IAccountRepository { public Task<SystemAccount?> FindLoginAsync(string e,string p)=>dao.FindLoginAsync(e,p); public Task<List<SystemAccount>> SearchAsync(string? q)=>dao.SearchAsync(q); public Task<SystemAccount?> GetAsync(short id)=>dao.GetAsync(id); public Task<bool> EmailExistsAsync(string email,short? excludeId)=>dao.EmailExistsAsync(email,excludeId); public Task SaveAsync(SystemAccount x,bool add)=>dao.SaveAsync(x,add); public Task<bool> DeleteAsync(short id)=>dao.DeleteAsync(id); }
public interface ICategoryRepository { Task<List<Category>> SearchAsync(string? q); Task<Category?> GetAsync(short id); Task AddAsync(Category x); Task UpdateAsync(Category x); Task<bool> DeleteAsync(short id); }
public class CategoryRepository(CategoryDAO dao) : ICategoryRepository { public Task<List<Category>> SearchAsync(string? q)=>dao.SearchAsync(q); public Task<Category?> GetAsync(short id)=>dao.GetAsync(id); public Task AddAsync(Category x)=>dao.SaveAsync(x,true); public Task UpdateAsync(Category x)=>dao.SaveAsync(x,false); public Task<bool> DeleteAsync(short id)=>dao.DeleteAsync(id); }
public interface ITagRepository { Task<List<Tag>> GetAllAsync(); }
public class TagRepository(TagDAO dao) : ITagRepository { public Task<List<Tag>> GetAllAsync()=>dao.GetAllAsync(); }
public interface INewsRepository { Task<List<NewsArticle>> SearchAsync(string? q,bool activeOnly); Task<NewsArticle?> GetAsync(string id); Task SaveAsync(NewsArticle x,IEnumerable<int> tags,bool add); Task DeleteAsync(string id); Task<List<NewsArticle>> ReportAsync(DateTime from,DateTime to); }
public class NewsRepository(NewsDAO dao) : INewsRepository { public Task<List<NewsArticle>> SearchAsync(string? q,bool a)=>dao.SearchAsync(q,a); public Task<NewsArticle?> GetAsync(string id)=>dao.GetAsync(id); public Task SaveAsync(NewsArticle x,IEnumerable<int> t,bool a)=>dao.SaveAsync(x,t,a); public Task DeleteAsync(string id)=>dao.DeleteAsync(id); public Task<List<NewsArticle>> ReportAsync(DateTime f,DateTime t)=>dao.ReportAsync(f,t); }
