using Microsoft.AspNetCore.Mvc;
using NguyenHoangNgocChauBusinessObjects.Models;
using NguyenHoangNgocChauBusinessObjects.Services;
namespace NguyenHoangNgocChauMVC.Controllers;
public class CategoriesController(ICategoryService s) : BaseController { public async Task<IActionResult> Index(string? q){var d=Require(1);if(d!=null)return d;ViewBag.Query=q;return View(await s.SearchAsync(q));} [HttpPost] public async Task<IActionResult> Save(Category x){if(Require(1) is { } d)return d;if(!ModelState.IsValid){TempData["Error"]="Invalid category.";return RedirectToAction(nameof(Index));}if(x.CategoryId==0)await s.AddAsync(x);else await s.UpdateAsync(x);TempData["Success"]="Category saved.";return RedirectToAction(nameof(Index));} [HttpPost] public async Task<IActionResult> Delete(short id){if(Require(1) is { } d)return d;var ok=await s.DeleteAsync(id);TempData[ok?"Success":"Error"]=ok?"Category deleted.":"Cannot delete a category used by news.";return RedirectToAction(nameof(Index));} }
public class AccountsController(IAccountService s) : BaseController { public async Task<IActionResult> Index(string? q){if(Require(0) is { } d)return d;ViewBag.Query=q;return View(await s.SearchAsync(q));} [HttpPost] public async Task<IActionResult> Save(SystemAccount x){if(Require(0) is { } d)return d;if(!ModelState.IsValid){TempData["Error"]="Invalid account.";return RedirectToAction(nameof(Index));}var saved=await s.SaveAsync(x,x.AccountId==0);TempData[saved?"Success":"Error"]=saved?"Account saved.":"Account already exists.";return RedirectToAction(nameof(Index));} [HttpPost] public async Task<IActionResult> Delete(short id){if(Require(0) is { } d)return d;var deleted=await s.DeleteAsync(id);TempData[deleted?"Success":"Error"]=deleted?"Account deleted.":"Cannot delete this account because it is used by news articles.";return RedirectToAction(nameof(Index));} }
public class NewsController(INewsService s, ICategoryService cs) : BaseController { public async Task<IActionResult> Index(string? q){ViewBag.Query=q;ViewBag.Categories=await cs.SearchAsync(null);ViewBag.Tags=await s.TagsAsync();return View(await s.SearchAsync(q,Role!=1));} public async Task<IActionResult> Details(string id){var news=await s.GetAsync(id);if(news is null)return NotFound();if(Role!=1&&Role!=0&&news.NewsStatus!=true)return NotFound();return View(news);} [HttpPost] public async Task<IActionResult> Save(NewsArticle x,int[]? tagIds){if(Require(1) is { } d)return d;if(!ModelState.IsValid){TempData["Error"]="Invalid news.";return RedirectToAction(nameof(Index));}await s.SaveAsync(x,tagIds??[],AccountId!.Value,await s.GetAsync(x.NewsArticleId)==null);TempData["Success"]="News saved.";return RedirectToAction(nameof(Index));} [HttpPost] public async Task<IActionResult> Delete(string id){if(Require(1) is { } d)return d;await s.DeleteAsync(id);TempData["Success"]="News deleted.";return RedirectToAction(nameof(Index));} public async Task<IActionResult> History(){if(Require(1) is { } d)return d;return View((await s.SearchAsync(null)).Where(x=>x.CreatedById==AccountId));} }
public class ReportsController(INewsService s) : BaseController { public async Task<IActionResult> Index(DateTime? startDate,DateTime? endDate){if(Require(0) is { } d)return d;if(startDate.HasValue&&endDate.HasValue){if(startDate>endDate){ModelState.AddModelError("","Start date must not exceed end date.");return View();}return View(await s.ReportAsync(startDate.Value,endDate.Value));}return View(new List<NewsArticle>());} }
public class ProfileController(IAccountService s) : BaseController { public async Task<IActionResult> Index(){if(Require(1) is { } d)return d;return View(await s.GetAsync(AccountId!.Value));} [HttpPost] public async Task<IActionResult> Index(SystemAccount x){if(Require(1) is { } d)return d;var current=await s.GetAsync(AccountId!.Value);if(current==null)return NotFound();x.AccountId=current.AccountId;x.AccountRole=current.AccountRole;await s.SaveAsync(x,false);TempData["Success"]="Profile updated.";return RedirectToAction(nameof(Index));} }

