using NguyenHoangNgocChauBusinessObjects.Models;
using NguyenHoangNgocChauBusinessObjects.Repositories;

namespace NguyenHoangNgocChauBusinessObjects.Services;

public record AdminAccountOptions { public string Email { get; init; } = string.Empty; public string Password { get; init; } = string.Empty; public string Name { get; init; } = "Administrator"; }
public interface IAdminAccountProvider { AdminAccountOptions Account { get; } }
public sealed class AdminAccountProvider(AdminAccountOptions account) : IAdminAccountProvider { public AdminAccountOptions Account { get; } = account; }
public record LoginResult(short? AccountId, string Name, int Role);
public interface IAuthService { Task<LoginResult?> LoginAsync(string email, string password); }
public class AuthService(IAccountRepository accounts, IAdminAccountProvider admin) : IAuthService { public async Task<LoginResult?> LoginAsync(string email, string password) { if (email.Equals(admin.Account.Email, StringComparison.OrdinalIgnoreCase) && password == admin.Account.Password) return new(null, admin.Account.Name, 0); var a = await accounts.FindLoginAsync(email, password); return a is null ? null : new(a.AccountId, a.AccountName, a.AccountRole ?? -1); } }
public interface ICategoryService { Task<List<Category>> SearchAsync(string? q); Task<Category?> GetAsync(short id); Task AddAsync(Category x); Task UpdateAsync(Category x); Task<bool> DeleteAsync(short id); }
public class CategoryService(ICategoryRepository repo) : ICategoryService { public Task<List<Category>> SearchAsync(string? q)=>repo.SearchAsync(q); public Task<Category?> GetAsync(short id)=>repo.GetAsync(id); public Task AddAsync(Category x)=>repo.AddAsync(x); public Task UpdateAsync(Category x)=>repo.UpdateAsync(x); public Task<bool> DeleteAsync(short id)=>repo.DeleteAsync(id); }
public interface IAccountService { Task<List<SystemAccount>> SearchAsync(string? q); Task<SystemAccount?> GetAsync(short id); Task<bool> SaveAsync(SystemAccount x, bool isNew); Task<bool> DeleteAsync(short id); }
public class AccountService(IAccountRepository repo) : IAccountService { public Task<List<SystemAccount>> SearchAsync(string? q)=>repo.SearchAsync(q); public Task<SystemAccount?> GetAsync(short id)=>repo.GetAsync(id); public async Task<bool> SaveAsync(SystemAccount x,bool isNew){x.AccountEmail=x.AccountEmail.Trim();if(await repo.EmailExistsAsync(x.AccountEmail,isNew?null:x.AccountId))return false;await repo.SaveAsync(x,isNew);return true;} public Task<bool> DeleteAsync(short id)=>repo.DeleteAsync(id); }
public interface INewsService { Task<List<NewsArticle>> SearchAsync(string? q, bool activeOnly=false); Task<NewsArticle?> GetAsync(string id); Task SaveAsync(NewsArticle x, IEnumerable<int> tags, short staffId, bool isNew); Task DeleteAsync(string id); Task<List<Tag>> TagsAsync(); Task<List<NewsArticle>> ReportAsync(DateTime from, DateTime to); }
public class NewsService(INewsRepository repo, ITagRepository tags) : INewsService { public Task<List<NewsArticle>> SearchAsync(string? q,bool activeOnly=false)=>repo.SearchAsync(q,activeOnly); public Task<NewsArticle?> GetAsync(string id)=>repo.GetAsync(id); public async Task SaveAsync(NewsArticle x,IEnumerable<int> tagIds,short staffId,bool isNew){if(isNew){x.CreatedById=staffId;x.CreatedDate=DateTime.Now;}else{x.UpdatedById=staffId;x.ModifiedDate=DateTime.Now;}await repo.SaveAsync(x,tagIds,isNew);} public Task DeleteAsync(string id)=>repo.DeleteAsync(id); public Task<List<Tag>> TagsAsync()=>tags.GetAllAsync(); public Task<List<NewsArticle>> ReportAsync(DateTime from,DateTime to)=>repo.ReportAsync(from,to); }
